services:
  web:
    container_name: cms-backend
    build:
      context: ./app
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html/
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:LuPPdglE7DBYhooXbB9gQ1N7Fti0tnDYgAILw+qEi8s=
      - DB_CONNECTION=mysql
      - DB_HOST=cms-db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laraveluser
      - DB_PASSWORD=laravelpass
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: cms-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpass
    volumes:
      - mysql_data:/var/lib/mysql
    #   - ./mysql/my.cnf:/var/lib/mysql/my.cnf
    ports:
      - "3306:3306"

volumes:
  mysql_data:
    name: mysql
