name: Deploy to Server

on:
    push:
        branches: [ "master"]

jobs:
    deploy:
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout Code
          uses: actions/checkout@v3
    
        - name: Set up SSH
          uses: webfactory/ssh-agent@v0.5.3
          with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

        - name: Add known hosts
          run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts

        - name: Deploy to Server
          run: |
            ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'

            sudo su -
                
            # 一時的なアップロード先を準備
            cd /root/develop/
            git pull

            EOF